document.write("<center>");
document.write("<img align='center' width='1112' height='205' src='images/banner.jpg'>");
document.write("</center>");
document.write("<table align='center' width='1112' border='0'>");
document.write("<tr class='menu'>");
document.write("<td align='center' width='%14'><a href='index.html'>Home</a></td>");
document.write("<td align='center' width='%14%'><a href='about.html'>About</a></td>");
document.write("<td align='center' width='14%'><a href='shows.html'>Shows</a></td>");
document.write("<td align='center' width='17%'><a href='music.html'>Music<a/></td>");
document.write("<td align='center' width='14%'><a href='videos.html'>Video</a></td>");
document.write("<td align='center' width='14%'><a href='press.html'>Press</a></td>");
document.write("<td align='center' width='14%'><a href='contact.html'>Contact</a></td>");
document.write("</tr>");
document.write("</table>");
document.write("<br>");
document.write("<br>");
